[General]
dns-server = 223.5.5.5,114.114.114.114,8.8.8.8,1.1.1.1
skip-proxy = 127.0.0.1,localhost,*.local

[Rule]
DOMAIN-SUFFIX,openai.com,Proxy
DOMAIN-SUFFIX,chatgpt.com,Proxy
DOMAIN-KEYWORD,openai,Proxy
DOMAIN-SUFFIX,oaistatic.com,Proxy
# TikTok 相关
DOMAIN-SUFFIX,tiktok.com,Proxy
DOMAIN-SUFFIX,tiktokcdn.com,Proxy
DOMAIN-SUFFIX,tiktokv.com,Proxy
DOMAIN-SUFFIX,byteoversea.com,Proxy
DOMAIN-SUFFIX,ibytedtos.com,Proxy

FINAL,DIRECT
